const departmentsAndCities = [
    { department: "Amazonas", cities: ["Leticia"] },
    { department: "Antioquia", cities: ["Medellín","Bello","Envigado"] },
    { department: "Arauca", cities: ["Arauca"] },
    { department: "Atlántico", cities: ["Barranquilla"] },
    { department: "Bolívar", cities: ["Cartagena"] },
    { department: "Boyacá", cities: ["Tunja"] },
    { department: "Caldas", cities: ["Manizales"] },
    { department: "Caquetá", cities: ["Florencia"] },
    { department: "Casanare", cities: ["Yopal"] },
    { department: "Cauca", cities: ["Popayán"] },
    { department: "Cesar", cities: ["Valledupar"] },
    { department: "Chocó", cities: ["Quibdó"] },
    { department: "Córdoba", cities: ["Montería"] },
    { department: "Cundinamarca", cities: ["Bogotá"] },
    { department: "Guainía", cities: ["Inírida"] },
    { department: "Guaviare", cities: ["San José del Guaviare"] },
    { department: "Huila", cities: ["Neiva"] },
    { department: "La Guajira", cities: ["Riohacha"] },
    { department: "Magdalena", cities: ["Santa Marta"] },
    { department: "Meta", cities: ["Villavicencio"] },
    { department: "Nariño", cities: ["Pasto"] },
    { department: "Norte de Santander", cities: ["Cúcuta"] },
    { department: "Putumayo", cities: ["Mocoa"] },
    { department: "Quindío", cities: ["Armenia"] },
    { department: "Risaralda", cities: ["Pereira"] },
    { department: "San Andrés y Providencia", cities: ["San Andrés"] },
    { department: "Santander", cities: ["Bucaramanga", "Floridablanca", "Piedecuesta", "Giron","Lebrija"] },
    { department: "Sucre", cities: ["Sincelejo"] },
    { department: "Tolima", cities: ["Ibagué"] },
    { department: "Valle del Cauca", cities: ["Cali"] },
    { department: "Vaupés", cities: ["Mitú"] },
    { department: "Vichada", cities: ["Puerto Carreño"] },
  ];
  
  export default departmentsAndCities;
  